apiVersion: apps/v1
kind: Deployment
metadata:
  name: hodu-server
  labels:
    app: hodu-server
  namespace: hodu-dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hodu-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: hodu-server
    spec:
      serviceAccountName: hodu-server
      nodeSelector:
        kubernetes.io/arch: amd64
        phase: dev
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: dev
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/hodu/hodu-server:240812-1
        name: hodu-server
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hodu-server
  namespace: hodu-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/DevHoduAccessRole
---
apiVersion: v1
kind: Service
metadata:
  namespace: hodu-dev
  name: hodu-server
spec:
  type: ClusterIP
  selector:
    app: hodu-server
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: hodu-dev
  name: hodu-server
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - hodu-dev.wafflestudio.com
  - hodu-server
  http:
  - route:
    - destination:
        host: hodu-server
