apiVersion: v1
kind: Namespace
metadata:
  name: coupong-prod
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupong
  labels:
    app: coupong
  namespace: coupong-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupong
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: coupong
    spec:
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
        - image: pfcjeong/coupong:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: coupong
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 200m
              memory: 384Mi
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: coupong-prod
  name: coupong
spec:
  type: ClusterIP
  selector:
    app: coupong
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: coupong-prod
  name: coupong
spec:
  gateways:
    - istio-ingress/waffle-ingressgateway
    - mesh
  hosts:
    - coupong-api.wafflestudio.com
  http:
    - route:
        - destination:
            host: coupong
