apiVersion: apps/v1
kind: Deployment
metadata:
  name: waffledotcom-server
  labels:
    app: waffledotcom-server
  namespace: waffledotcom-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waffledotcom-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: waffledotcom-server
    spec:
      serviceAccountName: waffledotcom-server
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
        - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/waffledotcom-prod/waffledotcom-server:v1.0.2
          name: waffledotcom-server
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waffledotcom-server
  namespace: waffledotcom-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/waffledotcom-server-prod-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: waffledotcom-prod
  name: waffledotcom-server
spec:
  type: ClusterIP
  selector:
    app: waffledotcom-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: waffledotcom-prod
  name: waffledotcom-server
spec:
  gateways:
    - istio-ingress/waffle-ingressgateway
    - mesh
  hosts:
    - wadot-api.wafflestudio.com
  http:
    - route:
        - destination:
            host: waffledotcom-server
