apiVersion: v1
kind: Namespace
metadata:
  name: snutt-dev
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: snutt-prod
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: guam
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: sso-dev
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: sso-prod
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: seminar
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: webgam-dev
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: feelin-dev
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: siksha-dev
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: siksha-prod
  labels:
    istio-injection: enabled
