apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.pupuri-bot: |
    url: https://pupuri-api.wafflestudio.com/argocd/webhook-endpoint
    method: POST
    headers:
      - name: Content-Type
        value: application/json

  templates.sync-completed: |-
    {{`{"namespace":"`}}{{"{{.app.metadata.namespace}}"}}{{`","app":"`}}{{"{{.app.metadata.name}}"}}{{`"}`}}

  triggers.sync-completed: |-
    - description: Application sync completed
      oncePer: app
      when: app.status.operationState.phase in ['Succeeded']
      send:
        - webhook:pupuri-bot

  subscriptions.sync-completed: |-
    recipients:
      - pupuri-bot

  controller.disableAnnotations: "true"

