apiVersion: apps/v1
kind: Deployment
metadata:
  name: wacruit-server
  labels:
    app: wacruit-server
  namespace: wacruit-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wacruit-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: wacruit-server
    spec:
      serviceAccountName: wacruit-server
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
        - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/wacruit-prod/wacruit-server:7
          name: wacruit-server
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wacruit-server
  namespace: wacruit-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/wacruit-prod-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: wacruit-prod
  name: wacruit-server
spec:
  type: ClusterIP
  selector:
    app: wacruit-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: wacruit-prod
  name: wacruit-server
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - wacruit-server.wacruit-prod.svc.cluster.local
  http:
  - route:
    - destination:
        host: wacruit-server
