apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-all-role
  namespace: snutt-dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-all-role-binding
  namespace: snutt-dev

roleRef:
  kind: Role
  name: pod-all-role
  apiGroup: rbac.authorization.k8s.io

subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: snutt-developers
