apiVersion: apps/v1
kind: Deployment
metadata:
  name: wacruit-server
  labels:
    app: wacruit-server
  namespace: wacruit-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wacruit-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: wacruit-server
    spec:
      serviceAccountName: wacruit-server
      containers:
        - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/wacruit-dev/wacruit-server:3
          name: wacruit-server
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wacruit-server
  namespace: wacruit-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/wacruit-dev-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: wacruit-dev
  name: wacruit-server
spec:
  type: ClusterIP
  selector:
    app: wacruit-server
  ports:
    - port: 80
      targetPort: 8080
