apiVersion: apps/v1
kind: Deployment
metadata:
  name: ggzz-server
  labels:
    app: ggzz-server
  namespace: ggzz-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ggzz-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: ggzz-server
    spec:
      serviceAccountName: ggzz-server
      nodeSelector:
        phase: dev
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: dev
      containers:
        - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/ggzz-dev/ggzz-server:19
          name: ggzz-server
          resources:
            requests:
              cpu: 100m
              memory: 458Mi
            limits:
              cpu: 200m
              memory: 458Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ggzz-server
  namespace: ggzz-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/ggzz-dev-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: ggzz-dev
  name: ggzz-server
spec:
  type: ClusterIP
  selector:
    app: ggzz-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: ggzz-dev
  name: ggzz-server
spec:
  gateways:
    - istio-ingress/waffle-ingressgateway
    - mesh
  hosts:
    - ggzz-api-dev.wafflestudio.com
  http:
    - route:
        - destination:
            host: ggzz-server
