apiVersion: apps/v1
kind: Deployment
metadata:
  name: snutt-core
  labels:
    app: snutt-core
  namespace: snutt-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snutt-core
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: snutt-core
    spec:
      serviceAccountName: snutt-core
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt-dev/snutt-core:108
        name: snutt-core
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snutt-core
  namespace: snutt-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/snutt-core-dev-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: snutt-dev
  name: snutt-core
spec:
  type: NodePort
  selector:
    app: snutt-core
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: snutt-dev
  name: snutt-core
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  hosts:
  - snutt-api-dev.wafflestudio.com
  http:
  - route:
    - destination:
        host: snutt-core
