apiVersion: batch/v1
kind: CronJob
metadata:
  name: snutt-timetable-batch-coursebook
  labels:
    app: snutt-timetable-batch-coursebook
  namespace: snutt-dev
spec:
  concurrencyPolicy: Forbid
  schedule: "0 */12 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            phase: batch
          tolerations:
            - effect: NoSchedule
              key: phase
              operator: Equal
              value: batch
          restartPolicy: OnFailure
          serviceAccountName: snutt-timetable-batch
          containers:
          - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt-dev/snutt-timetable-batch:359
            name: snutt-timetable-batch-coursebook
            resources:
              requests:
                cpu: 200m
                memory: 2Gi
              limits:
                cpu: 1000m
                memory: 2Gi
            env:
            - name: JOB_NAME
              value: "sugangSnuMigrationJob"
            - name: JAVA_OPTS
              value: "-XX:InitialRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0 -Duser.timezone=UTC -Djavax.net.ssl.trustStore=/usr/local/openjdk-17/lib/security/cacerts"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: TRUFFLE_ENABLED
              value: "true"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: snutt-timetable-batch-user-nickname
  labels:
    app: snutt-timetable-batch-user-nickname
  namespace: snutt-dev
spec:
  concurrencyPolicy: Forbid
  schedule: "0 0 31 2 *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            phase: batch
          tolerations:
            - effect: NoSchedule
              key: phase
              operator: Equal
              value: batch
          restartPolicy: OnFailure
          serviceAccountName: snutt-timetable-batch
          containers:
          - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt-dev/snutt-timetable-batch:359
            name: snutt-timetable-batch-user-nickname
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                cpu: 1000m
                memory: 1Gi
            env:
            - name: JOB_NAME
              value: "userNicknameCreateJob"
            - name: JAVA_OPTS
              value: "-XX:InitialRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0 -Duser.timezone=UTC"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: TRUFFLE_ENABLED
              value: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snutt-timetable-batch
  namespace: snutt-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/snutt-timetable-batch-dev-role
