apiVersion: apps/v1
kind: Deployment
metadata:
  name: siksha-api-server
  labels:
    app: siksha-api-server
  namespace: siksha-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siksha-api-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: siksha-api-server
    spec:
      serviceAccountName: siksha-api-server
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/siksha-prod/siksha-api-server:9
        name: siksha-api-server
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: siksha-api-server
  namespace: siksha-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/siksha-api-server-prod-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: siksha-prod
  name: siksha-api-server
spec:
  type: ClusterIP
  selector:
    app: siksha-api-server
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: siksha-prod
  name: siksha-api-server
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  hosts:
  - siksha-api-k8s.wafflestudio.com
  http:
  - route:
    - destination:
        host: siksha-api-server
