apiVersion: apps/v1
kind: Deployment
metadata:
  name: memowithtags-server
  labels:
    app: memowithtags-server
  namespace: memowithtags-dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: memowithtags-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: memowithtags-server
    spec:
      serviceAccountName: memowithtags
      nodeSelector:
        kubernetes.io/arch: amd64
        phase: dev
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: dev
      containers:
        - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/memowithtags-dev/memowithtags-server:16
          name: memowithtags-server
          env:
            - name: JAVA_OPTS
              value: "-XX:InitialRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 512Mi
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/startup
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: memowithtags
  namespace: memowithtags-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/memowithtags-dev-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: memowithtags-dev
  name: memowithtags-server
spec:
  type: ClusterIP
  selector:
    app: memowithtags-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: memowithtags-dev
  name: memowithtags-server
spec:
  gateways:
    - istio-ingress/waffle-ingressgateway
    - mesh
  hosts:
    - memowithtags-api-dev.wafflestudio.com
  http:
    - route:
        - destination:
            host: memowithtags-server
