apiVersion: batch/v1
kind: CronJob
metadata:
  name: siksha-crawler
  labels:
    app: siksha-crawler
  namespace: siksha-prod
spec:
  concurrencyPolicy: Forbid
  schedule: "0 20 * * *" 
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: OnFailure
          containers:
          - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/siksha-prod/siksha-crawler:1
            name: siksha-crawler
