_format_version: "3.0"

services:
- name: account-service
  url: http://account-server.sso-prod.svc.cluster.local
  routes:
  - name: account-service
    paths:
    - /account-service/
  - name: account-web-cf
    hosts:
    - sso.wafflestudio.com
    paths:
    - /api/account-service/
  plugins:
  - name: waffle-jwt-authorizer

- name: truffle-service
  url: http://truffle-dashboard.truffle-prod.svc.cluster.local
  routes:
  - name: truffle-web-cf
    hosts:
    - truffle.wafflestudio.com
    paths:
    - /api/
    strip_path: false
  plugins:
  - name: waffle-jwt-authorizer

- name: wacruit-service
  url: http://wacruit-server.wacruit-prod.svc.cluster.local
  routes:
  - name: wacruit-web-cf
    hosts:
    - wacruit.wafflestudio.com
    paths:
    - /api/
  plugins:
  - name: waffle-jwt-authorizer

- name: wacruit-service-dev
  url: http://wacruit-server.wacruit-dev.svc.cluster.local
  routes:
  - name: wacruit-web-cf
    hosts:
    - wacruit-dev.wafflestudio.com
    paths:
    - /api/
  plugins:
  - name: waffle-jwt-authorizer
