apiVersion: apps/v1
kind: Deployment
metadata:
  name: snutt-ev
  labels:
    app: snutt-ev
  namespace: snutt-prod
spec:
  # replicas: HPA
  selector:
    matchLabels:
      app: snutt-ev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: snutt-ev
    spec:
      serviceAccountName: snutt-ev
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt-prod/snutt-ev:10
        name: snutt-ev
        resources:
          requests:
            cpu: 200m
            memory: 768Mi
          limits:
            cpu: 400m
            memory: 768Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8080
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8080
        startupProbe:
          httpGet:
            path: /health-check
            port: 8080
          failureThreshold: 10
        env:
        - name: JAVA_OPTS
          value: "-XX:InitialRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0 -Duser.timezone=UTC"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: TRUFFLE_ENABLED
          value: "true"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snutt-ev-hpa
  labels:
    app: snutt-ev
  namespace: snutt-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snutt-ev
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snutt-ev
  namespace: snutt-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/snutt-ev-prod-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: snutt-prod
  name: snutt-ev
spec:
  type: ClusterIP
  selector:
    app: snutt-ev
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: snutt-prod
  name: snutt-ev
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - snutt-ev-api.wafflestudio.com
  http:
  - timeout: 10s
    match:
    - uri:
        prefix: /swagger-ui
    - uri:
        prefix: /v3/api-docs
    route:
    - destination:
        host: snutt-ev
