apiVersion: apps/v1
kind: Deployment
metadata:
  name: siksha-spring-server
  labels:
    app: siksha-spring-server
  namespace: siksha-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siksha-spring-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: siksha-spring-server
    spec:
      serviceAccountName: siksha-spring-server
      nodeSelector:
        kubernetes.io/arch: arm64
        phase: dev
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: dev
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/siksha-dev/siksha-spring-server:24
        name: siksha-spring-server
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 30
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: siksha-spring-server
  namespace: siksha-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/siksha-api-server-dev-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: siksha-dev
  name: siksha-spring-server
spec:
  type: ClusterIP
  selector:
    app: siksha-spring-server
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: siksha-dev
  name: siksha-spring-server
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - siksha-server-dev.wafflestudio.com
  http:
  - route:
    - destination:
        host: siksha-spring-server
