apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.17.2
    helm:
      releaseName: cert-manager
      valuesObject:
        crds:
          enabled: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  syncPolicy:
    {{- .Values.spec.syncPolicy | toYaml | nindent 4 }}
    syncOptions:
    - CreateNamespace=true
