apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: truffle
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: apps/truffle-prod/truffle-consumer
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    {{- .Values.spec.syncPolicy | toYaml | nindent 4 }}
