apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: wacruit-server
  annotations:
    notifications.argoproj.io/subscribe.sync-completed.pupuri-bot:"true"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: apps/wacruit-prod/wacruit-server
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    {{- .Values.spec.syncPolicy | toYaml | nindent 4 }}
