apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgam-server
  labels:
    app: webgam-server
  namespace: webgam-dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: webgam-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: webgam-server
    spec:
      serviceAccountName: webgam-server
      nodeSelector:
        phase: dev
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: dev
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/webgam-dev/webgam-server:4
        name: webgam-server
        resources:
          requests:
            cpu: 100m
            memory: 480Mi
          limits:
            cpu: 200m
            memory: 480Mi
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webgam-server
  namespace: webgam-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/webgam-server-dev-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: webgam-dev
  name: webgam-server
spec:
  type: ClusterIP
  selector:
    app: webgam-server
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: webgam-dev
  name: webgam-server
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - webgam-api-dev.wafflestudio.com
  http:
  - route:
    - destination:
        host: webgam-server
