apiVersion: apps/v1
kind: Deployment
metadata:
  name: snugo-server
  labels:
    app: snugo-server
  namespace: snugo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snugo-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: snugo-server
    spec:
      serviceAccountName: snugo-server
      nodeSelector:
        phase: dev
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: dev
      containers:
        - image: # TODO: ECR 주소 추가
          name: snugo-server
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 100m
              memory: 192Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snugo-server
  namespace: snugo
---
apiVersion: v1
kind: Service
metadata:
  namespace: snugo
  name: snugo-server
spec:
  type: ClusterIP
  selector:
    app: snugo-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: snugo
  name: snugo-server
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - snugo-api.wafflestudio.com
  http:
  - route:
    - destination:
        host: snugo-server
