apiVersion: apps/v1
kind: Deployment
metadata:
  name: snutt-core
  labels:
    app: snutt-core
  namespace: snutt-prod
spec:
  # replicas: HPA
  selector:
    matchLabels:
      app: snutt-core
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: snutt-core
    spec:
      serviceAccountName: snutt-core
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt-prod/snutt-core:84
        name: snutt-core
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health-check
            port: 3000
        readinessProbe:
          httpGet:
            path: /health-check
            port: 3000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: snutt-core-hpa
  labels:
    app: snutt-core
  namespace: snutt-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snutt-core
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snutt-core
  namespace: snutt-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/snutt-core-prod-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: snutt-prod
  name: snutt-core
spec:
  type: ClusterIP
  selector:
    app: snutt-core
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: snutt-prod
  name: snutt-core
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - snutt-api.wafflestudio.com
  http:
  - name: "prod-snutt-timetable-route"
    timeout: 10s
    match:
    ############## migrated apis ############
    - method:
        exact: GET
      uri:
        regex: ^(?:\/v1)?\/tables\/?$
    - uri:
        regex: ^(?:\/v1)?\/auth\/register_local\/?$
    - uri:
        regex: ^(?:\/v1)?\/auth\/login_local\/?$
    - uri:
        regex: ^(?:\/v1)?\/auth\/logout\/?$
    - uri:
        regex: ^(?:\/v1)?\/search_query\/?$
    - uri:
        regex: ^(?:\/v1)?\/user\/device(\/.*)?$
    - uri:
        regex: ^(?:\/v1)?\/notification(\/.*)?$
    - uri:
        regex: ^(?:\/v1)?\/admin/insert_noti\/?$
    ################# new apis ##############
    - uri:
        regex: ^\/v1\/bookmarks(\/.*)?$
    - uri:
        regex: ^\/v1\/configs(\/.*)?$
    - uri:
        regex: ^\/v1\/friends(\/.*)?$
    - uri:
        regex: ^\/v1\/admin\/configs(\/.*)?$
    route:
    - destination:
        host: snutt-timetable
    corsPolicy:
      allowHeaders:
        - content-type
        - x-access-apikey
        - x-access-token
      allowMethods:
        - POST
        - GET
        - PUT
        - DELETE
        - OPTIONS
      allowOrigins:
        - exact: 'https://snutt.wafflestudio.com'
        - exact: 'https://snutt-admin.wafflestudio.com'
  - name: "snutt-core-route"
    timeout: 10s
    route:
    - destination:
        host: snutt-core
