apiVersion: apps/v1
kind: Deployment
metadata:
  name: pupuri-bot
  labels:
    app: pupuri-bot
  namespace: pupuri-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pupuri-bot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: pupuri-bot
    spec:
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/pupuri-prod/pupuri-bot:52
        name: pupuri-bot
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: pupuri-prod
  name: pupuri-bot
spec:
  type: ClusterIP
  selector:
    app: pupuri-bot
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: pupuri-prod
  name: pupuri-bot
spec:
  gateways:
    - istio-ingress/waffle-ingressgateway
    - mesh
  hosts:
    - pupuri-api.wafflestudio.com
  http:
    - route:
        - destination:
            host: pupuri-bot
