apiVersion: apps/v1
kind: Deployment
metadata:
  name: feelin-web
  labels:
    app: feelin-web
  namespace: feelin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feelin-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: feelin-web
    spec:
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/feelin-prod/feelin-web:19
        name: feelin-web
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: feelin-prod
  name: feelin-web
spec:
  type: ClusterIP
  selector:
    app: feelin-web
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: feelin-prod
  name: feelin-web
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - feelin.wafflestudio.com
  http:
  - route:
    - destination:
        host: feelin-web
