apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
  namespace: k8s-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: k8s-monitoring-sa
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
        - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/k8s-monitoring:0.0.1
          imagePullPolicy: Always
          name: app
          envFrom:
            - secretRef:
                name: k8s-monitoring-secret
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 250Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-monitoring-sa
  namespace: k8s-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-monitoring-cluster-role
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
      - cronjobs
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-monitoring-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-monitoring-cluster-role
subjects:
  - kind: ServiceAccount
    name: k8s-monitoring-sa
    namespace: k8s-monitoring
