apiVersion: apps/v1
kind: Deployment
metadata:
  name: wacruit-judge-worker
  labels:
    app: wacruit-judge-worker
  namespace: wacruit-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wacruit-judge-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: wacruit-judge-worker
    spec:
      containers:
      - image: waffledotcom-judge:latest
        imagePullPolicy: Never
        name: wacruit-judge-worker
        command: ["./scripts/workers"]
        envFrom:
        - configMapRef:
            name: wacruit-judge-config
        securityContext:
          privileged: true