apiVersion: apps/v1
kind: Deployment
metadata:
  name: wacruit-judge-server
  labels:
    app: wacruit-judge-server
  namespace: wacruit-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wacruit-judge-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: wacruit-judge-server
    spec:
      serviceAccountName: wacruit-judge-server
      containers:
      - image: waffledotcom-judge:latest
        imagePullPolicy: Never
        name: wacruit-judge-server
        ports:
        - containerPort: 2358
        envFrom:
        - configMapRef:
            name: wacruit-judge-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wacruit-judge-server
  namespace: wacruit-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/wacruit-judge-dev-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: wacruit-dev
  name: wacruit-judge-server
spec:
  # type: ClusterIP
  # selector:
  #   app: wacruit-judge-server
  # ports:
  # - port: 80
  #   targetPort: 2358
  type: NodePort
  selector:
    app: wacruit-judge-server
  ports:
  - port: 2358
    targetPort: 2358
    nodePort: 30000
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   namespace: wacruit-dev
#   name: wacruit-judge-server
# spec:
#   gateways:
#   - istio-ingress/waffle-ingressgateway
#   hosts:
#   - wacruit-judge-dev.wafflestudio.com
#   http:
#   - match:
#     - uri:
#         exact: /docs/index.html
#     route:
#     - destination:
#         host: wacruit-judge-server
