apiVersion: apps/v1
kind: Deployment
metadata:
  name: wacruit-judge-server
  labels:
    app: wacruit-judge-server
  namespace: wacruit-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wacruit-judge-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: wacruit-judge-server
    spec:
      serviceAccountName: wacruit-judge-server
      nodeSelector:
        phase: dev
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: dev
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/wacruit-dev/wacruit-judge-server:22
        name: wacruit-judge-server
        resources:
          requests:
            cpu: 100m
            memory: 192Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
          - containerPort: 2358
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wacruit-judge-server
  namespace: wacruit-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/wacruit-dev-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: wacruit-dev
  name: wacruit-judge-server
spec:
  type: ClusterIP
  selector:
    app: wacruit-judge-server
  ports:
  - port: 80
    targetPort: 2358
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: wacruit-dev
  name: wacruit-judge-server
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - wacruit-judge-server.wacruit-dev.svc.cluster.local
  - wacruit-judge-api-dev.wafflestudio.com # TODO: For debugging, remove before 2023/08/04
  http:
  - route:
    - destination:
        host: wacruit-judge-server
