apiVersion: apps/v1
kind: Deployment
metadata:
  name: areyouhere-server
  labels:
    app: areyouhere-server
  namespace: areyouhere
spec:
  replicas: 0
  selector:
    matchLabels:
      app: areyouhere-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: areyouhere-server
    spec:
      nodeSelector:
        phase: dev
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: dev
      containers:
        - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/areyouhere/areyouhere-server:94
          name: areyouhere-server
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: areyouhere
  name: areyouhere-server
spec:
  type: ClusterIP
  selector:
    app: areyouhere-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: areyouhere
  name: areyouhere-server
spec:
  gateways:
    - istio-ingress/waffle-ingressgateway
    - mesh
  hosts:
    - areyouhere-api.wafflestudio.com
  http:
    - route:
        - destination:
            host: areyouhere-server
