apiVersion: apps/v1
kind: Deployment
metadata:
  name: feelin-social-server
  labels:
    app: feelin-social-server
  namespace: feelin-dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: feelin-social-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: feelin-social-server
    spec:
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/feelin-dev/feelin-social-server:29
        name: feelin-social-server
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-XX:InitialRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0"
---
apiVersion: v1
kind: Service
metadata:
  namespace: feelin-dev
  name: feelin-social-server
spec:
  type: ClusterIP
  selector:
    app: feelin-social-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: feelin-dev
  name: feelin-social-server
spec:
  gateways:
    - istio-ingress/waffle-ingressgateway
    - mesh
  hosts:
    - feelin-social-api-dev.wafflestudio.com
  http:
    - route:
        - destination:
            host: feelin-social-server
