apiVersion: apps/v1
kind: Deployment
metadata:
  name: snutt-timetable
  labels:
    app: snutt-timetable
  namespace: snutt-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snutt-timetable
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: snutt-timetable
    spec:
      serviceAccountName: snutt-timetable
      nodeSelector:
        phase: dev
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: dev
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt-dev/snutt-timetable:279
        name: snutt-timetable
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 512Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8080
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8080
        startupProbe:
          httpGet:
            path: /health-check
            port: 8080
          failureThreshold: 20
        env:
        - name: JAVA_OPTS
          value: "-XX:InitialRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0 -Duser.timezone=UTC"
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: TRUFFLE_ENABLED
          value: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snutt-timetable
  namespace: snutt-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/snutt-timetable-dev-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: snutt-dev
  name: snutt-timetable
spec:
  type: ClusterIP
  selector:
    app: snutt-timetable
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: snutt-dev
  name: snutt-timetable
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - snutt-api-dev.wafflestudio.com
  http:
  - name: "legacy-route"
    timeout: 10s
    match:
    - uri:
        regex: ^(?:\/v1)?\/course_books(\/.*)?$
    - uri:
        regex: ^(?:\/v1)?\/colors(\/.*)?$
    - uri:
        regex: ^(?:\/v1)?\/auth\/request_temp\/?$
    - uri:
        regex: ^(?:\/v1)?\/auth\/login_apple\/?$
    - uri:
        regex: ^(?:\/v1)?\/admin\/change_pw\/?$
    - uri:
        regex: ^(?:\/v1)?\/admin\/recent_fcm_log\/?$
    - uri:
        regex: ^(?:\/v1)?\/admin\/coursebooks\/?$
    - uri:
        regex: ^(?:\/v1)?\/admin\/statistics\/?$
    - uri:
        regex: ^(?:\/v1)?\/ev-service(\/.*)?$
    - uri:
        regex: ^(?:\/v1)?\/feedback\/?$
    route:
    - destination:
        host: snutt-core
  - name: "dev-snutt-timetable-route"
    timeout: 10s
    route:
    - destination:
        host: snutt-timetable
    corsPolicy:
      allowHeaders:
      - content-type
      - x-access-apikey
      - x-access-token
      - x-app-version
      - x-app-type
      - x-os-type
      - x-os-version
      - x-device-id
      - x-device-model
      allowMethods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
      allowOrigins:
      - exact: 'https://snutt-dev.wafflestudio.com'
      - exact: 'https://snutt-admin-dev.wafflestudio.com'
      - exact: 'https://snutt-ev-web-dev.wafflestudio.com'
