apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: snutt-ev-batch-lecture-sync
  labels:
    app: snutt-ev-batch-lecture-sync
  namespace: snutt-prod
spec:
  concurrencyPolicy: Forbid
  schedule: "0 19 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: snutt-ev-batch
          containers:
          - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt-prod/snutt-ev-batch:57
            name: snutt-ev-batch-lecture-sync
            env:
            - name: JOB_NAMES
              value: "SYNC_JOB"
            - name: JAVA_OPTS
              value: "-Duser.timezone=UTC"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: snutt-ev-batch-snuev-migration
  labels:
    app: snutt-ev-batch-snuev-migration
  namespace: snutt-prod
spec:
  concurrencyPolicy: Forbid
  suspend: true
  # 실행 방법
  # kubectl create job snutt-ev-batch-snuev-migration --from=cronjob/snutt-ev-batch-snuev-migration
  schedule: "0 0 31 2 *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: snutt-ev-batch
          containers:
          - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt-prod/snutt-ev-batch:57
            name: snutt-ev-batch-snuev-migration
            env:
            - name: JOB_NAMES
              value: "SNUEV_MIGRATION_JOB"
            - name: JAVA_OPTS
              value: "-Duser.timezone=UTC"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snutt-ev-batch
  namespace: snutt-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/snutt-ev-cron-prod-role
