apiVersion: apps/v1
kind: Deployment
metadata:
  name: feelin-web
  labels:
    app: feelin-web
  namespace: feelin-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feelin-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: feelin-web
    spec:
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/feelin-dev/feelin-web:7
        name: feelin-web
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: feelin-dev
  name: feelin-web
spec:
  type: ClusterIP
  selector:
    app: feelin-web
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: feelin-dev
  name: feelin-web
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  hosts:
  - feelin-dev.wafflestudio.com
  http:
  - route:
    - destination:
        host: feelin-web
