apiVersion: apps/v1
kind: Deployment
metadata:
  name: snutt-ev-web
  labels:
    app: snutt-ev-web
  namespace: snutt-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snutt-ev-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: snutt-ev-web
    spec:
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/snutt-dev/snutt-ev-web:190
        imagePullPolicy: Always
        name: snutt-ev-web
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: snutt-dev
  name: snutt-ev-web
spec:
  type: NodePort
  selector:
    app: snutt-ev-web
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: snutt-dev
  name: snutt-ev-web
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  hosts:
  - snutt-ev-web-dev.wafflestudio.com
  http:
  - route:
    - destination:
        host: snutt-ev-web
