apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-project-backend
  labels:
    app: react-project-backend
  namespace: seminar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-project-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: react-project-backend
    spec:
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/seminar/react-project-backend:5
        name: react-project-backend
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: seminar
  name: react-project-backend
spec:
  type: ClusterIP
  selector:
    app: react-project-backend
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: seminar
  name: react-project-backend
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - seminar-react-api.wafflestudio.com
  http:
  - route:
    - destination:
        host: react-project-backend
