apiVersion: batch/v1
kind: CronJob
metadata:
  name: siksha-crawler
  labels:
    app: siksha-crawler
  namespace: siksha-dev
spec:
  concurrencyPolicy: Forbid
  schedule: "0 20 * * 0"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
            phase: batch
          tolerations:
            - effect: NoSchedule
              key: phase
              operator: Equal
              value: batch
          restartPolicy: OnFailure
          containers:
          - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/siksha-dev/siksha-crawler:42
            name: siksha-crawler
