apiVersion: apps/v1
kind: Deployment
metadata:
  name: siksha-spring-server
  labels:
    app: siksha-spring-server
  namespace: siksha-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siksha-spring-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: siksha-spring-server
    spec:
      serviceAccountName: siksha-spring-server
      nodeSelector:
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/siksha-prod/siksha-spring-server
        name: siksha-spring-server
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 512Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: siksha-spring-server
  namespace: siksha-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::405906814034:role/siksha-spring-server-prod-role
---
apiVersion: v1
kind: Service
metadata:
  namespace: siksha-prod
  name: siksha-spring-server
spec:
  type: ClusterIP
  selector:
    app: siksha-spring-server
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: siksha-prod
  name: siksha-spring-server
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - siksha-server.wafflestudio.com
  http:
  - route:
    - destination:
        host: siksha-spring-server