apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guam
  namespace: argocd
spec:
  description: Guam Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: guam
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
    - group: ''
      kind: Service
  orphanedResources:
    warn: false
  roles:
    - name: admin
      description: Admin for Team Guam
      policies:
        - p, proj:guam:admin, applications, *, guam/*, allow
        - p, proj:guam:admin, clusters, get, *, allow
        - p, proj:guam:admin, repositories, get, *, allow
        - p, proj:guam:admin, repositories, create, *, allow
        - p, proj:guam:admin, repositories, update, *, allow
        - p, proj:guam:admin, repositories, delete, *, allow
      groups:
        - wafflestudio:Guam
