apiVersion: apps/v1
kind: Deployment
metadata:
  name: android-project-backend
  labels:
    app: android-project-backend
  namespace: seminar
spec:
  replicas: 0
  selector:
    matchLabels:
      app: android-project-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: android-project-backend
    spec:
      containers:
      - image: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com/seminar/android-project-backend:1
        name: android-project-backend
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: seminar
  name: android-project-backend
spec:
  type: ClusterIP
  selector:
    app: android-project-backend
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: seminar
  name: android-project-backend
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - seminar-android-api.wafflestudio.com
  http:
  - route:
    - destination:
        host: android-project-backend
